### ISSUE TITLE
Oscar's code review

### ISSUE THREAD

**Issue by RuriEnciso** [oovillagran/Portfolio-project#9]
Hi @oovillagran  ,

Good job so far! 🚀 
There are some issues that you still need to work on to go to the next project but you are almost there! 👌 

![tufoin](https://media.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif)

## Highlights
✅  Good implementation 
✅  Your design looks like Figmas
✅  Commits are descriptive

## Required Changes ♻️
- The X button has to be placed in the right corner, and it has to be responsive. Please check that when you choose and option from the menu you have to go to that section but the popup Menu has to disappear.
- I think it would be better if you add the footer section to this part as the figma design.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this issue. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in this issue thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by oovillagran** [comment]
Thank you @RuriEnciso, I appreciate your suggestions. I will work on those recomendations to improve my project.
